server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://62.109.21.174/service
    username: service
    password: service
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always