services:
  aggrewater-service:
    build: main-service
    container_name: aggrewater-service
    ports:
      - "8080:8080"
    depends_on:
      - aggw-db
    entrypoint:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aggw-db:5433/service
      - SPRING_DATASOURCE_USERNAME=service
      - SPRING_DATASOURCE_PASSWORD=service

  aggw-db:
    image: postgres:16.1
    container_name: postgres-aggw-service-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=service
      - POSTGRES_USER=service
      - POSTGRES_DB=service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10