services:
#  users-service:
#    build: ./gateway
#    container_name: users-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - aggw-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://aggw-db:5432/users
#      - SPRING_DATASOURCE_USERNAME=users
#      - SPRING_DATASOURCE_PASSWORD=users

  aggw-db:
    image: postgres:16.1
    container_name: aggw-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=users
      - POSTGRES_USER=users
      - POSTGRES_DB=users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10