CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255),
    name VARCHAR(255) UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS token_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(512) NOT NULL,
    data_created DATE NOT NULL,
    end_data DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    token_access_id BIGINT UNIQUE REFERENCES token_access(id),
    updated_at TIMESTAMP(6),
    password VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_roles (
    roles_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (roles_id, user_id)
);

-- Populate roles if they do not exist
INSERT INTO roles (name)
VALUES ('ROLE_ADMIN'), ('ROLE_USER'), ('ROLE_SELLER')
ON CONFLICT (name) DO NOTHING;